extern char menuactive, whoisptr, bcs;
extern int atkp,defp,magp,mgrp,hitp,dodp,mblp,ferp,reap;

void border(int x, int y, int x2, int y2);
void menubox(int x, int y, int x2, int y2);
void tmenubox(int x, int y, int x2, int y2);
void DrawPartyStats();
void DrawMainMenu(int ptr);
int WhoIs(int i);
void ReOrder(int i);
void StatusScreen(char cz);
void MainMenu();
void Volume();
void SystemMenu();
void PutBuySellBox(char p);
void PutGPBox();
void PutCharBox(char a,char b, char c, char d, char e, char p);
void PutMessageBox(char *str);
void PutItemName(char *str);
void PutItemDesc(char *str);
void PutEquipBox(char c);
void PutItemBox(char l);
void SellMenu();
void SellCharItem(char c);
void ConfirmSell(char c, char ptr);
void PutStoreInv();
void PutBuyCharBox(char ptr, char p);
void BuyMenu(char p);
void CalcBuyEquipPreview(int a,int i);
void PutEquipPreview(char c, char ptr);
void BuyItem(char ptr);
void PurchaseItem(char c, char i);
void BuyOrBuyEquip(char c, char ptr);

void greyscale(int width, int height, unsigned char *src, unsigned char *dest);
void LoadSaveErase(char mode);
void RemoveItem(char c, char i);
void DrawItemMenu(char c,char ptr);
void ItemGive(char c, char p);
void ItemUse(char c, char p);
void ItemActionSelect(char c,char p);
void ItemMenu(char c);
extern int atkp,defp,magp,mgrp,hitp,dodp,mblp,ferp,reap;
void CalcEquipPreview(int a,int i,int p);
void DrawEquipMenu(char c,char ptr);
void Equip(char c,char ptr);
void DeEquip(char c,char ptr);
void EquipMenu(char c);
